openapi: 3.0.1
info:
  title: Ballerina GraphQL Services
  version: 0.1.0
servers:
  - url: http://localhost:8090
    description: Greeting and User Creation Service
  - url: http://localhost:8091
    description: User Details Service
paths:
  /:
    post:
      summary: GraphQL endpoint for Greeting Service
      operationId: getGreeting
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  example: "query GreetWorld{ greeting(name:\"World\") }"
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object

  /user:
    post:
      summary: GraphQL endpoint for User Details Service
      operationId: getUserDetails
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  example: "query GetUser{ userDetails(name:\"World\") }"
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object